# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
#
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "tests"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run tests
        run: pnpm test
